spring:
  profiles:
    active: dev
---
spring:
  profile: dev
  datasource:
    url: jdbc:h2:mem:kanbandb
    username: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
